### ISSUE TITLE
feat(Tabs): new component and preset

### ISSUE THREAD

**Issue by mnenie** [una-ui/una-ui#144]
### 🆒 Your use case

I can take it on myself.

<img width="931" alt="Снимок экрана 2024-07-25 в 22 33 17" src="https://github.com/user-attachments/assets/56c86a14-43ed-4b02-9f01-1c299ad1481e">

### 🆕 The solution you'd like

So, I think I'll make some components which will contain: 
- wrapper
- triggers
- content (I'll  think on this about it in more detail)

### ℹ️ Additional info

In making this. We will use https://www.radix-vue.com/components/tabs.html for instant unstyled component.

Consider this as a guide when making this component: https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/tabs ✨ 

Here's an example to what I did to [Slider](https://unaui.com/components/slider#component) using https://radix-vue.com/

### 🏗️  Todos

- [x] Add component (ref: https://unaui.com/components/slider#component)
- [x] Add presets (ref: https://unaui.com/components/slider#presets)
- [x] Add props (ref: https://unaui.com/components/slider#props)
- [x] Add docs
- [x] Add examples

**Comment by phojie** [comment]
Hello mate, I have added additional info to the PR description. Please take a look and let me know if you need anything else. 

Thanks, man! @mnenie 🔥

**Comment by mnenie** [comment]
> Hello mate, I have added additional info to the PR description. Please take a look and let me know if you need anything else.
> 
> Thanks, man! @mnenie 🔥

@phojie hello!

how to distribute everything that relates to tabs in the sense that conditionally we have 4 separate components (Tabs, Tabs Trigger, TabsContent, TabsList) and we can make in /runtime/components/elements folder tabs

and as for types and styles we can make separate files: tabs.ts, tabsTrigger.ts, tabsContent.ts, tabsList.ts or describe everything in one file and it will contain conditionally NTabsProps, NTabListProps, etc ?

**Comment by phojie** [comment]
> > Hello mate, I have added additional info to the PR description. Please take a look and let me know if you need anything else.
> > Thanks, man! @mnenie 🔥
> 
> @phojie hello!
> 
> how to distribute everything that relates to tabs in the sense that conditionally we have 4 separate components (Tabs, Tabs Trigger, TabsContent, TabsList) and we can make in /runtime/components/elements folder tabs
> 
> and as for types and styles we can make separate files: tabs.ts, tabsTrigger.ts, tabsContent.ts, tabsList.ts or describe everything in one file and it will contain conditionally NTabsProps, NTabListProps, etc ?

Hello @mnenie,

Wow, great question!

Suppose we only have one main component (NTabs) and others are considered subcomponents. So let's structure the components like this:

- elements/
     - tabs/
           - Index.vue or Tabs.vue (either will work for NTabs) -> MainComponent (Bringing all subcomponents together)
           - TabsRoot.vue (Tabs.vue -> renamed to TabsRoot) (NTabsRoot) ref: https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/tabs/Tabs.vue
           - TabsTrigger.vue (NTabsTrigger)
           - TabList.vue (NTabsList)
           - TabsContent.vue (NTabsContent)
           - etc...

> Though they are composed of several components, we can still consider it as one component (NTabs). Following the Single Responsibility Principle from the SOLID principles, we will still have one preset and one type file.
 
EG of presets:

```ts
export const staticTabs: Record<`${TabsPrefix}-${string}` | TabsPrefix, string> = {
  // configurations
  'tabs': 'tabs-primary size-base',
  'tabs-disabled': 'n-disabled',

  // components
  'tabs-root': '',
  'tabs-trigger': '',
  'tabs-list': '',
  'tabs-content': '',
}
```

EG of types:

```.ts
export interface NTabsProps {
  // main types
}

export interface NTabsRootProps {
  // types for tabsroot
}

.... etc...

(this is all belong to 1 file (tabs.ts)
```

and lastly dont forget to add imports to the entire folder of Tabs inside elements folder.


```.ts 
// module.ts

addComponentsDir({
      path: resolve(runtimeDir, 'components/elements', 'tabs'),
      prefix: options.prefix,
      global: options.global,
      watch: nuxt.options.dev,
    })
```

Let me know if you have any further questions! 💛
