### ISSUE TITLE
refactor(Checkbox): accept `indeterminate` option and use `NLabel` component.

### ISSUE THREAD

**Issue by phojie** [una-ui/una-ui#179]
## Todos

- [x] Accept `indeterminate` value.
- [x] Use `NLabel` component for the label.
- [x] Use `v-model:checked` to define reactive value insteaed of `v-model`.
- [x] Update preset configuration
